apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx
spec:
  selector:
    app: nginx-app   # Use the appropriate label to match your pod
  ports:
    - protocol: TCP
      port: 80       # Port in the service
      targetPort: 80 # Port in the pod
      nodePort: 31007 # Port  exposed in Node. The service will be accessible from this port of node. (30000-32767 range)
  type: NodePort
